#!/bin/bash -eu

lftp -d -u $USER,$PASS $HOST -e "\
  set ssl:check-hostname false; \
  mirror \
  --reverse \
  --delete \
  --verbose \
  --parallel=12 \
  -X .DS_Store \
  $LOCAL_DIR \
  $REMOTE_DIR; \
  exit"
  
