name: deploy

on:
  push:
    branches: [ main ]
  repository_dispatch:
    branches: [ main ]
    types: [ blog_post ]

jobs:
  cleanup-runs:
    runs-on: ubuntu-latest
    steps:
      - uses: rokroskar/workflow-run-cleanup-action@v0.3.0
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
    if: "!startsWith(github.ref, 'refs/tags/')"

  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Check out repository
        uses: actions/checkout@v2.3.4

      - name: 🚚 Setup node
        uses: actions/setup-node@v2.1.4

      - name: 🔨 Build Project
        run: |
          npm install
          touch .env
          echo -e "API_KEY='${{ secrets.api_key }}'\n" >> .env
          npm run generate --if-present
          which lftp || sudo apt-get update -y && sudo apt-get install lftp -y

      - name: 📂 Run ftp_upload
        run: |
          HOST="${{ secrets.FTP_SERVER }}" \
          USER="${{ secrets.FTP_USERNAME }}" \
          PASS="${{ secrets.FTP_PASSWORD }}" \
          LOCAL_DIR="./dist/" \
          REMOTE_DIR="${{ secrets.ftp_server_dir }}" ./.github/ftp_upload
